// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyqADUPbmEvVEQYN2r0tPjt5BqnRvwZw',
    appId: '1:242708736363:web:fcdd004e0276eee1b2442e',
    messagingSenderId: '242708736363',
    projectId: 'chat-app-4a1b4',
    authDomain: 'chat-app-4a1b4.firebaseapp.com',
    storageBucket: 'chat-app-4a1b4.appspot.com',
    measurementId: 'G-2Y3V3WKJ8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLRay75ls5-CsGuTrxTpR6VCe9qE2nFs',
    appId: '1:242708736363:android:e259a38439c6e475b2442e',
    messagingSenderId: '242708736363',
    projectId: 'chat-app-4a1b4',
    storageBucket: 'chat-app-4a1b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsX-tDuHd2vq2HL8mIgkgX8sexVsoKm3w',
    appId: '1:242708736363:ios:bf18ece883880d8fb2442e',
    messagingSenderId: '242708736363',
    projectId: 'chat-app-4a1b4',
    storageBucket: 'chat-app-4a1b4.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsX-tDuHd2vq2HL8mIgkgX8sexVsoKm3w',
    appId: '1:242708736363:ios:e54fd8f45db18ee7b2442e',
    messagingSenderId: '242708736363',
    projectId: 'chat-app-4a1b4',
    storageBucket: 'chat-app-4a1b4.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
